# Generated by Django 4.0.3 on 2022-04-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=25)),
                ('noofppl', models.CharField(max_length=24)),
                ('subject', models.TextField()),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
