# Generated by Django 4.0.3 on 2022-04-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='subject',
            new_name='descr',
        ),
    ]
